apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort:

